models:
  - name: churn-gb
    kind: predictor
    source:
      provider: local
      file: ./models/churn_gb.joblib
    predictor:
      task: classification # regression | classification
      schema:
        features:
          - { name: age, type: float }
          - { name: income, type: float }
          - { name: region, type: int }

server:
  host: localhost
  port: 8081
  api_key: ${SIMPLE_LOCAL_API_KEY}
