import hashlib
import shutil
import subprocess
import tempfile
from pathlib import Path

from .. import config as config_mod
from .config import (
    BASE_IMAGE_ENV,
    BASE_SYSTEM_PACKAGES,
    CONFIG_NAMES,
    DIGEST_LENGTH,
    DOCKERIGNORE,
    EXCLUDED_NAMES,
    EXCLUDED_SUFFIXES,
    EXPOSED_PORT,
    IMAGE_CONFIG_PATH,
    LLAMA_BASE_IMAGE,
    LLAMA_IMAGE_ENV,
    VENV_PATH,
    WHEELS_PATH,
    WORKDIR,
)
from .spec import Build, Deploy, default_base_image, load_served, resolve


class BuildError(RuntimeError):
    pass


def _repo_root() -> Path | None:
    root = Path(__file__).resolve().parents[2]
    return root if (root / "pyproject.toml").exists() else None


def package_requirement(build: Build) -> str:
    """What the image installs simple-local from. An explicit pin is what you
    want in production — it is the rollback story for the runtime itself, which
    is a separate axis from rolling back a config."""
    extras = f"[{','.join(sorted(build.extras))}]" if build.extras else ""
    if build.package:
        return build.package if extras and extras in build.package else f"{build.package}{extras}"
    return f"wheel:simple-local{extras}"


def _staged_files(directory: Path) -> list[Path]:
    files = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file():
            continue
        if any(part in EXCLUDED_NAMES for part in path.relative_to(directory).parts):
            continue
        if path.suffix in EXCLUDED_SUFFIXES or path.name in EXCLUDED_NAMES:
            continue
        if path.name in CONFIG_NAMES and path.parent == directory:
            continue
        files.append(path)
    return files


def render_dockerfile(deploy: Deploy, served: config_mod.Config | None = None) -> str:
    build = deploy.build
    base = build.base_image or default_base_image(served)
    env = dict(LLAMA_IMAGE_ENV if base == LLAMA_BASE_IMAGE else {"PATH": BASE_IMAGE_ENV["PATH"]})
    env.update({k: v for k, v in BASE_IMAGE_ENV.items() if k != "PATH"})
    env["CONFIG"] = IMAGE_CONFIG_PATH
    env.update(build.env)

    packages = " ".join([*BASE_SYSTEM_PACKAGES, *sorted(build.system_packages)])
    requirement = package_requirement(build)
    install = (
        f"{WHEELS_PATH}/*.whl{'[' + ','.join(sorted(build.extras)) + ']' if build.extras else ''}"
        if requirement.startswith("wheel:")
        else requirement
    )

    lines = [
        f"# Generated by simple-local from {Path(deploy.container_config).name}.",
        "# Do not edit: change the deploy.build block in the config instead.",
        f"FROM {base}",
        "",
        "ENV " + " \\\n    ".join(f'{k}="{v}"' for k, v in env.items()),
        "",
        f"WORKDIR {WORKDIR}",
        "",
        "RUN apt-get update \\",
        f"    && apt-get install -y --no-install-recommends {packages} \\",
        "    && rm -rf /var/lib/apt/lists/* \\",
        "    && curl -LsSf https://astral.sh/uv/install.sh | sh",
        "",
        "# The venv lives outside WORKDIR on purpose: Container Apps runs a",
        "# recursive chown over WORKDIR before start with a ~3 minute budget, and",
        "# torch and CUDA wheels are enough files to blow it.",
        f"RUN uv venv {VENV_PATH}",
        "",
    ]

    if requirement.startswith("wheel:"):
        lines += [f"COPY wheels {WHEELS_PATH}", ""]
    if build.requirements:
        lines += [
            f"RUN uv pip install --python {VENV_PATH} " + " ".join(sorted(build.requirements)),
            "",
        ]
    lines += [
        f"RUN uv pip install --python {VENV_PATH} {install}",
        "",
        f"COPY . {WORKDIR}",
        "",
    ]
    if build.prefetch:
        lines += [
            "# Weights are baked in so a cold start is model-load only.",
            f"RUN {VENV_PATH}/bin/simple-local download -c {IMAGE_CONFIG_PATH}",
            "",
        ]
    lines += [
        f"EXPOSE {EXPOSED_PORT}",
        f'ENTRYPOINT ["{VENV_PATH}/bin/simple-local", "serve", "-c", "{IMAGE_CONFIG_PATH}"]',
        "",
    ]
    return "\n".join(lines)


def image_digest(deploy: Deploy, served: config_mod.Config | None = None) -> str:
    """Identifies what a build would produce, so `plan` can tell a stale image
    from a current one without building to find out. It covers the generated
    Dockerfile, the served config, and every other file in the model directory.

    It deliberately does *not* hash the simple-local wheel's contents — only the
    requirement string — so editing the package source during development does
    not force a rebuild on every plan. Bump the pin, or `apply --rebuild`.
    """
    directory = Path(deploy.directory)
    digest = hashlib.sha256()
    digest.update(render_dockerfile(deploy, served).encode())
    digest.update(Path(deploy.container_config).read_bytes())
    for path in _staged_files(directory):
        digest.update(str(path.relative_to(directory)).encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()[:DIGEST_LENGTH]


def _build_wheel(destination: Path) -> Path:
    root = _repo_root()
    if root is None:
        raise BuildError(
            "cannot build a simple-local wheel outside the source tree — "
            "set deploy.build.package to a pinned version or a git URL"
        )
    destination.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run(
        ["uv", "build", "--wheel", "--out-dir", str(destination)],
        cwd=root,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise BuildError((proc.stderr or proc.stdout).strip())
    wheels = sorted(destination.glob("*.whl"))
    if not wheels:
        raise BuildError(f"uv build produced no wheel in {destination}")
    return wheels[-1]


def stage(deploy: Deploy, served: config_mod.Config | None = None) -> Path:
    """Assembles a self-contained build context: the model directory's files, the
    served config under one canonical name, a generated Dockerfile, and the
    simple-local wheel when the config has not pinned a published version."""
    directory = Path(deploy.directory)
    context = Path(tempfile.mkdtemp(prefix="simple-local-build-"))

    for path in _staged_files(directory):
        target = context / path.relative_to(directory)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target)

    (context / CONFIG_NAMES[0]).write_text(Path(deploy.container_config).read_text())
    (context / "Dockerfile").write_text(render_dockerfile(deploy, served))
    (context / ".dockerignore").write_text(DOCKERIGNORE)

    if package_requirement(deploy.build).startswith("wheel:"):
        _build_wheel(context / "wheels")
    return context


def stage_for(config_path: str | Path) -> tuple[Deploy, Path]:
    deploy = resolve(config_path)
    return deploy, stage(deploy, load_served(deploy).config)
